receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4322"

exporters:
  file:
    path: "testGrpc_OperationFailed_metrics.txt"

service:
  extensions: []
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [file]