on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - library_generation/**

  workflow_dispatch:
name: verify_library_generation
jobs:
  verify_library_generation:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: [ 8 ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
        cache: maven
    - name: checkout googleapis
      run: |
        git clone -q https://github.com/googleapis/googleapis.git
        cd googleapis
        git checkout 90a551c2a02613507a2f0f05fd25d133113a1a1c
    - name: copy protos to proto_path
      run: |
        cp -r googleapis/google library_generation
    - name: generate java-aiplatform
      shell: bash
      run: |
        set -x
        library_generation/generate_library.sh \
        -p google/cloud/aiplatform/v1 \
        -d google-cloud-aiplatform-v1-java \
        --gapic_generator_version 2.24.0 \
        --protobuf_version 23.2 \
        --grpc_version 1.55.1 \
        --transport grpc \
        --rest_numeric_enums false \
        --include_samples true
    - name: checkout googleapis-gen
      run: |
        git clone https://cloud-java-bot:${{ secrets.CLOUD_JAVA_BOT_GITHUB_TOKEN }}@github.com/googleapis/googleapis-gen.git
        cd googleapis-gen
        git checkout 30620b4f34713860083fff036982900b1004cbf5
    - name: compare generation result
      run: |
        # ignore gradle files
        diff -r googleapis-gen/google/cloud/aiplatform/v1/google-cloud-aiplatform-v1-java/ library_generation/google-cloud-aiplatform-v1-java/ -x "*gradle*"
