on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - gapic-generator-java/library-generation/**
name: verify_library_generation
jobs:
  verify_library_generation:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: [ 11 ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
        cache: maven
    - name: maven install
      run: |
        mvn install -B -ntp -DskipTests -Dclirr.skip -Dcheckstyle.skip
    - name: setup showcase
      run: |
        git clone https://github.com/googleapis/gapic-showcase.git
        cd gapic-showcase
        # Using hardcoded versions from sdk-platform-java v2.24.0 (showcase references this version)
        git checkout v0.28.2
      working-directory: gapic-showcase
    - name: generate showcase
      run: |
        # Using hardcoded versions from sdk-platform-java v2.24.0 (showcase references this version)
        bash gapic-generator-java/library-generation/generate_library.sh \
            --proto-location $(pwd)/gapic-showcase/schema/google/showcase/v1beta1/ \
            --destination-location $(pwd)/showcase \
            --gapic-generator-java-version "2.24.0" \
            --protobuf-version "23.2" \
            --grpc-version "1.56.1" \
            --transport "grpc+rest"
    - name: compare generation result (This fails if any diff exists)
      run: |
        git diff showcase
      working-directory: sdk-platform-java
