on:
  push:
    branches:
    - main
  pull_request:
name: verify_library_generation
jobs:
  verify_library_generation:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: [ 11 ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
        cache: maven
    - name: maven install
      run: |
        mvn install -B -ntp -DskipTests -Dclirr.skip -Dcheckstyle.skip
    - name: get gapic-generator-java, protobuf, grpc version
      run: |
        set -x
        sudo apt-get update
        sudo apt-get install libxml2-utils
        echo "GENERATOR_VERSION=$(xmllint --xpath "string(//*[local-name()='version'])" gapic-generator-java-pom-parent/pom.xml)" >> $GITHUB_ENV
        echo "PROTOBUF_VERSION=$(xmllint --xpath "string(//*[local-name()='protobuf.version'])" gapic-generator-java-pom-parent/pom.xml)" >> $$GITHUB_ENV
        echo "GRPC_VERSION=$(xmllint --xpath "string(//*[local-name()='grpc.version'])" gapic-generator-java-pom-parent/pom.xml)" >> $$GITHUB_ENV
    - name: clone googleapis
      run: |
        git clone https://github.com/googleapis/googleapis.git
    - name: checkout a commit hash in googleapis
      run: |
        git checkout de4d95879fe000e75977f782e5104014934bbbfa
      working-directory: googleapis
    - name: clone google-cloud-java
      run: |
        git clone https://github.com/googleapis/google-cloud-java.git
    - name: checkout a commit hash in google-cloud-java
      run: |
        git checkout c7011dbd69189330de1c2946b736cd712d5c1f4e
      working-directory: google-cloud-java
    - name: remove contents in destination path
      run: |
        rm -rf java-aiplatform
      working-directory: google-cloud-java
    - name: generate java-aiplatform
      run: |
        library_generation/generate_library.sh
    - name: compare generation result
      run: |
        git diff java-aiplatform
      working-directory: google-cloud-java